spring:
  application:
    name: ohho02
  datasource:
    url: jdbc:postgresql://localhost:5433/ohho02
    driver-class-name: org.postgresql.Driver
    username: ohho
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
