spring:
  application:
    name: ohho02
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:~/test
    driver-class-name: org.h2.Driver
    username: sa
    password: secret
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show-sql: true
        format-sql: true

mybatis:
  mapper-locations: classpath:mybatis/mapper/h2/**/*.xml
  type-handlers-package: dev.ohhonim.ohho02.mapper.typehandler
  type-aliases-package: dev.ohhonim.ohho02.model
  configuration:
    map-underscore-to-camel-case: true
    default-statement-timeout: 30
    default-fetch-size: 100
